version: '3.1'
services:
  postgresql:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5423:5432"
    expose: 
      - "5432"
      - "5423"
  ruby:
    image: ruby:2.5.0
    environment:
      RACK_ENV: DEV
      RUBYLIB: ./lib
      DATABASE_URL_LOCAL: postgres://postgres:postgres@localhost:5422/postgres
    build: .
    command: rackup config.ru -E DEV
    ports:
      - "9595:9595"
    depends_on:
      - postgresql
    links:
      - postgresql
    volumes:
      - .:/myapp